force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Cuando un alquiler se completa guarda el registro que indica si la factura se genero con exito y si se envio al cliente, y en caso de no ser asi guarda la descripcion del error que haya sucedido</description>
    <label>Log</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/VRT_LKP_Rent__c.field-meta.xml
<CustomField>
    <fullName>VRT_LKP_Rent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Alquiler con el que esta relacionado  el log</description>
    <label>Alquiler</label>
    <referenceTo>VRT_Rental__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/VRT_SEL_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>VRT_SEL_Event_Type__c</fullName>
    <description>Descrive el tipo de Update, Creacion del registro, o diferentes updates.</description>
    <label>Tipo de Evento</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Creación del Registro</fullName>
            </value>
            <value>
                <fullName>Alquiler Completado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/VRT_SEL_Result__c.field-meta.xml
<CustomField>
    <fullName>VRT_SEL_Result__c</fullName>
    <description>Nos dice si el evento ha sido exitoso o no.</description>
    <label>Resultado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exito</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/VRT_TXT_Description__c.field-meta.xml
<CustomField>
    <fullName>VRT_TXT_Description__c</fullName>
    <description>Breve descripción del evento</description>
    <label>Descripcion</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VRT_Rental__c/VRT_Rental__c.object-meta.xml
<CustomObject>
    <description>Realiza el seguimiento de las operaciones de alquiler de los vehículos de la flota de la empresa.</description>
    <label>Alquiler</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Alquiler Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alquileres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/VRT_CLS_RentalPDFGenerator.cls
/**
 * @author		jgoikoet (42 Urduliz)
 * @since		02/2023
 * @desc		Creates a PDF invoice when a rental is completedand sends
 *              an email to the customer wit this document attached
 * @history		02/07/2026 - jgoikoet - Created class
 */
public with sharing class VRT_CLS_RentalPDFGenerator {
    

    /**
     * @desc	checks the list is not null or empty
     * @param	rentalIds: List of rental Ids to chek
     */
    @invocableMethod(label='Generar y Adjuntar PDF de Factura' description='Crea un PDF desde Visualforce y lo guarda en Files del Rental')
    public static void generateInvoicePDF(List<Id> rentalIds){

        if (rentalIds == null || rentalIds.isEmpty()) return;

        createPDFAsync(rentalIds);

    }

    /**
     * @desc	creates the PDV invoice abd attachs it in the relared list of Files
     *          also creates a Log related record
     * @param	rentalIds: List of rental Ids to chek
     */
    @future(callout=true)
    private static void createPDFAsync(List<Id> rentalIds){

        List<ContentVersion> cvList = new List<ContentVersion>();
        List<Log__c> logs = new List<Log__c>();

        Map<Id, VRT_Rental__c> rentalsMaps = new Map<Id, VRT_Rental__c>([
            SELECT Id, Name, VRT_LKP_Account__r.VRT_TXT_Email__c, VRT_LKP_Account__r.Name
            FROM VRT_Rental__c
            WHERE Id IN :rentalIds 
        ]);

        Map<Id, Blob> pdfBlobsMap = new Map<Id, Blob>();

        for (Id rentalId : rentalIds){

            PageReference pdfPage = Page.FacturaRentalPDF;//visualforce page, PageReference references URLs
            pdfPage.getParameters().put('id', rentalId);

            Blob pdfBlob; //Binary Large Object

            Log__c log = new Log__c();
            log.VRT_LKP_Rent__c = rentalId;
            log.VRT_SEL_Result__c = 'Exito';
            log.VRT_SEL_Event_Type__c = 'Alquiler Completado';
            log.VRT_TXT_Description__c = 'El Alquiler se ha completado con exito';
            logs.add(log);

            try{
                pdfBlob = pdfPage.getContentAsPDF(); //esta invocacion provocaria un 'uncommitted work pending' si no fuese asincrona
            }
            catch (Exception e) {
                // Bloque de escape para que los test de Apex no fallen (getContentAsPDF no corre en tests)
                pdfBlob = Blob.valueOf('Test PDF Content');
            }

            pdfBlobsMap.put(rentalId, pdfBlob);

            //creates the archive on 'Files'
            ContentVersion cv = new ContentVersion();
            cv.Title = 'Factura_Rental_' + rentalId + '.pdf';
            cv.PathOnClient = 'Factura_' + rentalId + '.pdf';
            cv.VersionData = pdfBlob;

            //relates the archive with the rental
            cv.FirstPublishLocationId = rentalId;

            cvList.add(cv);
        }

        if(!cvList.isEmpty()){ insert cvList; }

        //creates and sends the email
        List<Messaging.SingleEmailMessage> emailsToSEnd = new List<Messaging.SingleEmailMessage>();
               
        for (Id rentalID : rentalIds){
            
            VRT_Rental__c rent = rentalsMaps.get(rentalID);
            Blob pdfFile = pdfBlobsMap.get(rentalID);
            
            String accountEmail = rent.VRT_LKP_Account__r.VRT_TXT_Email__c;
            if (String.isNotBlank(accountEmail)){
                
                String body = 
                    'Estimado/a ' + rent.VRT_LKP_Account__r.Name + ',<br/><br/>' +
                    'Le adjuntamos en este correo la factura en PDF correspondiente a su alquiler con referencia ' + rent.Name + '.<br/><br/>' +
                    'Muchas gracias por confiar en nosotros.<br/><br/>' +
                    'Un saludo.';

                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                email.setToAddresses(new String[] {accountEmail});
                email.setSubject('Factura del alquiler -' + rent.Name);
                email.setHtmlBody(body);

                Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
                attachment.setFileName('Factura_' + rent.Name + '.pdf');
                attachment.setBody(pdfFile);
                attachment.setContentType('application/pdf');

                email.setFileAttachments(new Messaging.EmailFileAttachment[] { attachment });

                emailsToSEnd.add(email);
            }
        }
        if(!emailsToSEnd.isEmpty()){
            
            List<Messaging.sendEmailResult> emailResults = Messaging.sendEmail(emailsToSEnd,false);

            for (Integer i = 0; i < emailsToSEnd.size(); i++){

                Messaging.sendEmailResult result = emailResults[i];
                Log__c log = new Log__c();
                log.VRT_LKP_Rent__c = rentalIds[i];
                log.VRT_SEL_Event_Type__c = 'Alquiler Completado';
                

                if (result.isSuccess()){
                    log.VRT_SEL_Result__c = 'Exito';
                    log.VRT_TXT_Description__c = 'El email con la factura adjunta se ha enviado correctamente.';
                } else {

                    log.VRT_SEL_Result__c = 'Error';
                    List<String> errores = new List<String>();
                    
                    for(Messaging.SendEmailError err : result.getErrors()){
                        errores.add(err.getStatusCode() + ': ' + err.getMessage());
                        log.VRT_TXT_Description__c = 'Email no enviado  | ' + String.join(errores, ' | ');
                    }
                }
                logs.add(log);
            }
            Database.insert(logs, false);
        }
    }

}